name: Update streams

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # This line adds the manual trigger

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: Instalando yt_dlp
        run: |
          pip install yt_dlp
        
      - name: update streams
        run: sh M3U/streams.sh

      - name: setup git config
        run: |
          git config user.name "M3UPT Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd M3U
          git add M3UPT.m3u
          git commit -m "Update streams"
          git push origin main
